<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>API operations dashboard</title><style>
:root{font-family:system-ui,sans-serif;color:#17383a;background:#f4f0e8}body{margin:0}header{background:#17383a;color:#f4f0e8;padding:1.3rem 4vw;display:flex;justify-content:space-between;align-items:center;gap:1rem}main{max-width:1500px;margin:0 auto;padding:2rem 4vw}h1,h2{margin:0 0 .5rem}h2{margin-top:2.5rem}.muted{color:#617071}.stats{display:flex;gap:1rem;flex-wrap:wrap;margin:1.5rem 0}.stat{background:#fff;padding:1rem 1.5rem;border-left:4px solid #e5b567;min-width:130px}.stat strong{display:block;font-size:1.7rem}.toolbar{display:flex;gap:.75rem;flex-wrap:wrap;margin:1rem 0}.toolbar input,.toolbar select,.password-form input{padding:.6rem;border:1px solid #b7c3bd;background:#fff}.button,button{padding:.6rem .9rem;background:#e5b567;border:0;color:#17383a;font-weight:700;cursor:pointer}.link-button{background:transparent;color:#f4f0e8;padding:0}.table-wrap{overflow:auto;background:#fff;border:1px solid #d7ddd6}table{border-collapse:collapse;width:100%;min-width:900px}th,td{text-align:left;padding:.8rem;border-bottom:1px solid #e5e8e3;vertical-align:top}th{background:#edf1ec;font-size:.82rem;text-transform:uppercase}.ok{color:#13795b}.fail{color:#b33d32}.pill{font-weight:700}.details{white-space:pre-wrap;max-width:400px;max-height:180px;overflow:auto;font:12px ui-monospace,monospace;background:#f5f7f4;padding:.5rem}.password-form{display:flex;gap:.5rem;flex-wrap:wrap}.password-form input{min-width:170px}.notice{background:#dcefe3;padding:.7rem;margin:1rem 0}.pagination{display:flex;gap:.5rem;list-style:none;padding:1rem 0}.pagination a,.pagination span{padding:.35rem .6rem;background:#fff;border:1px solid #d7ddd6;text-decoration:none;color:inherit}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}main{padding:1.25rem 3vw}}
</style></head>
<body><header><div><strong>Operations dashboard</strong><div class="muted" style="color:#b8cfca">API health, failures, and user access</div></div><form method="post" action="{{ route('dashboard.logout') }}">@csrf<button class="link-button" type="submit">Sign out</button></form></header>
<main><nav><a href="{{ route('dashboard') }}">API health</a> | <a href="{{ route('dashboard.vouchers') }}">Posted vouchers</a></nav><h1>Failed API requests</h1><p class="muted">Only failed requests are shown. This page refreshes automatically every 10 seconds when you are not entering data.</p>
@if (session('status'))<div class="notice">{{ session('status') }}</div>@endif @if (session('error'))<div class="notice error">{{ session('error') }}</div>@endif
<section class="stats"><div class="stat"><span>Total</span><strong>{{ $stats['total'] }}</strong></div><div class="stat"><span class="ok">Successful</span><strong>{{ $stats['success'] }}</strong></div><div class="stat"><span class="fail">Failed</span><strong>{{ $stats['failed'] }}</strong></div></section>
<form class="toolbar" method="get"><input name="path" value="{{ request('path') }}" placeholder="Filter by API path"><button type="submit">Filter</button><a class="button" href="{{ route('dashboard') }}">Clear</a><span class="muted" id="refresh-status" aria-live="polite">Auto-refresh enabled</span></form>
<div class="table-wrap"><table><thead><tr><th>Time</th><th>Result</th><th>Request</th><th>User</th><th>Reason</th><th>Request / response</th></tr></thead><tbody>
@forelse ($logs as $log)<tr><td>{{ $log->created_at?->format('Y-m-d H:i:s') }}<br><small>{{ $log->duration_ms }} ms</small></td><td class="pill {{ $log->success ? 'ok' : 'fail' }}">{{ $log->success ? 'SUCCESS' : 'FAILURE' }}<br>{{ $log->status_code ?? 'exception' }}</td><td><strong>{{ $log->method }}</strong><br>{{ $log->path }}</td><td>{{ $log->user?->email ?? 'Unauthenticated' }}</td><td class="fail">{{ $log->error_message ?: '-' }}</td><td><details><summary>View payloads</summary><div class="details">Request: {{ json_encode($log->request_body, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}

Response: {{ json_encode($log->response_body, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</div></details></td></tr>@empty<tr><td colspan="6">No API requests match this filter.</td></tr>@endforelse
</tbody></table></div>{{ $logs->links() }}
<h2>User credentials</h2><p class="muted">Passwords are never readable from the database. Enter a password to verify it, or set a new one.</p><div class="table-wrap"><table><thead><tr><th>Name</th><th>Username / email</th><th>Password check</th><th>Set new password</th></tr></thead><tbody>@forelse ($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td><form class="password-form" method="post" action="{{ route('dashboard.users.verify-password', $user) }}">@csrf<input name="password" type="password" placeholder="Existing password" required><button type="submit">Check password</button></form></td><td><form class="password-form" method="post" action="{{ route('dashboard.users.password', $user) }}">@csrf<input name="password" type="password" placeholder="New password" minlength="8" required><input name="password_confirmation" type="password" placeholder="Confirm password" minlength="8" required><button type="submit">Update password</button></form></td></tr>@empty<tr><td colspan="4">No users found.</td></tr>@endforelse</tbody></table></div>
</main><script>
setInterval(function () {
	var active = document.activeElement;
	var editing = active && ['INPUT', 'TEXTAREA', 'SELECT'].includes(active.tagName);
	var inspecting = document.querySelector('details[open]');
	if (!editing && !inspecting) {
		window.location.reload();
	} else {
		document.getElementById('refresh-status').textContent = 'Auto-refresh paused while you are working';
	}
}, 10000);
</script></body></html>
