<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Posted vouchers</title><style>
:root{font-family:system-ui,sans-serif;color:#17383a;background:#f4f0e8}body{margin:0}header{background:#17383a;color:#f4f0e8;padding:1.3rem 4vw;display:flex;justify-content:space-between;align-items:center;gap:1rem}main{max-width:1500px;margin:0 auto;padding:2rem 4vw}h1{margin:1rem 0 .5rem}.muted{color:#617071}.toolbar{display:flex;gap:.75rem;flex-wrap:wrap;margin:1rem 0}.toolbar input,.toolbar select{padding:.6rem;border:1px solid #b7c3bd;background:#fff}.button,button{padding:.6rem .9rem;background:#e5b567;border:0;color:#17383a;font-weight:700;cursor:pointer}.link-button{background:transparent;color:#f4f0e8;padding:0}.table-wrap{overflow:auto;background:#fff;border:1px solid #d7ddd6}table{border-collapse:collapse;width:100%;min-width:1150px}th,td{text-align:left;padding:.8rem;border-bottom:1px solid #e5e8e3;vertical-align:top}th{background:#edf1ec;font-size:.82rem;text-transform:uppercase}.pill{font-weight:700}.variance{color:#b33d32}.details{white-space:pre-wrap;max-width:460px;max-height:230px;overflow:auto;font:12px ui-monospace,monospace;background:#f5f7f4;padding:.5rem}.notice{background:#dcefe3;padding:.7rem;margin:1rem 0}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}main{padding:1.25rem 3vw}}
</style></head>
<body><header><div><strong>Operations dashboard</strong><div style="color:#b8cfca">Posted voucher review</div></div><form method="post" action="{{ route('dashboard.logout') }}">@csrf<button class="link-button" type="submit">Sign out</button></form></header>
<main><nav><a href="{{ route('dashboard') }}">API health</a> | <a href="{{ route('dashboard.vouchers') }}">Voucher review</a></nav><h1>Voucher review</h1><p class="muted">Filter submitted vouchers by business date and outlet manager. Pending review, approved, and variance vouchers are shown with their complete records.</p>
<form class="toolbar" method="get"><label>Date <input name="date" type="date" value="{{ $date }}" required></label><label>Manager <select name="manager"><option value="">All managers</option>@foreach ($managers as $manager)<option value="{{ $manager }}" @selected(request('manager') === $manager)>{{ $manager }}</option>@endforeach</select></label><button type="submit">Filter</button><a class="button" href="{{ route('dashboard.vouchers') }}">Today</a></form>
<div class="notice">{{ count($vouchers) }} submitted voucher(s) found for {{ $date }}.</div>
<div class="table-wrap"><table><thead><tr><th>Posted</th><th>Organization / outlet</th><th>Manager</th><th>Status</th><th>Bookkeeper review</th><th>Totals</th><th>Full details</th></tr></thead><tbody>
@forelse ($vouchers as $item) @php($voucher = $item['voucher']) @php($approval = $item['approval'])<tr><td>{{ $voucher->posted_at ?: $voucher->updated_at }}<br><small>Voucher date: {{ $voucher->date_key }}</small></td><td><strong>{{ $voucher->organization_name }}</strong><br>{{ $voucher->outlet_name }}<br><small>{{ $voucher->id }}</small></td><td>{{ $voucher->manager_name }}</td><td class="pill {{ $voucher->status === 'variance' ? 'variance' : '' }}">{{ strtoupper($voucher->status) }}</td><td>@if ($approval)<strong>{{ $approval->reviewer_name }}</strong><br><small>{{ $approval->reviewer_email }}</small><br><small>Approved: {{ $approval->created_at }}</small>@else<span>Pending review</span><br><small>Not approved yet</small>@endif</td><td>Sales: {{ number_format((int) $voucher->total_sales_minor) }}<br>Expenses: {{ number_format((int) $voucher->total_expenses_minor) }}<br>Variance: {{ number_format((int) $voucher->variance_minor) }}</td><td><details><summary>View complete details</summary><div class="details">Voucher: {{ json_encode($voucher, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}

Bookkeeper review: {{ json_encode($approval, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}

Expenses: {{ json_encode($item['expenses'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}

Journals: {{ json_encode($item['journals'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}

Audit events: {{ json_encode($item['auditEvents'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</div></details></td></tr>@empty<tr><td colspan="7">No posted vouchers match this filter.</td></tr>@endforelse
</tbody></table></div></main></body></html>
